import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./src/styles/theme.css";
import "./src/styles/globals.css";
import Navigation from "./src/components/UI/Navigation";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-cream">
        <header>
          <Navigation />
        </header>
        <main className="flex-1 max-w-7xl w-full mx-auto">{children}</main>
        <footer>
          <p> footer </p>
        </footer>
      </body>
    </html>
  );
}
