import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./src/styles/theme.css";
import "./src/styles/globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-cream max-w-7xl mx-auto">
        {children}
      </body>
    </html>
  );
}
