import type { Metadata } from "next";
import { Montserrat, Unica_One } from "next/font/google";
import "./src/styles/theme.css";
import "./src/styles/globals.css";
import Navigation from "./src/components/UI/Navigation";
import Cursor from "./src/components/UI/cursor";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const unica = Unica_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-unica",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${unica.variable} h-full antialiased`}
    >
      <body className="min-h-full max-w-screen overflow-x-hidden flex flex-col bg-cream">
        <header>
          <Navigation />
        </header>
        <main>
          <div>
            {/*<Cursor />*/}
            {children}
          </div>
        </main>
        <footer>
          <p> footer </p>
        </footer>
      </body>
    </html>
  );
}
